DROP DATABASE IF EXISTS m183;
CREATE DATABASE m183;

USE m183;

CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    prename VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    hash CHAR(128) NOT NULL,
    salt CHAR(16) NOT NULL
);
