DROP DATABASE IF EXISTS m183;
CREATE DATABASE m183;

USE m183;

CREATE TABLE user (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    prename VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    hash CHAR(128) NOT NULL,
    salt CHAR(16) NOT NULL
);
CREATE TABLE route (
    id INT AUTO_INCREMENT PRIMARY KEY,
    stationfrom VARCHAR(255) NOT NULL,
    stationto VARCHAR(255) NOT NULL,
    stationfromexternal INT NOT NULL,
    stationtoexternal INT NOT NULL,
    user_FK INT NOT NULL,
    FOREIGN KEY (user_FK) REFERENCES user(id)
);
CREATE TABLE station (
    id INT AUTO_INCREMENT PRIMARY KEY,
    external INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    user_FK INT NOT NULL,
    FOREIGN KEY (user_FK) REFERENCES user(id)
);
